apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: db-backup
            image: bitnami/postgresql:latest
            securityContext:
               runAsUser: 0 # Temporarily run as root to ensure we can write to the mounted volume easily
            envFrom:
            - secretRef:
                name: db-backup-secrets
            volumeMounts:
            - mountPath: /backups
              name: backup-storage
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -e
              DATE=$(date +%Y-%m-%dT%H-%M-%S)
              FILENAME="/backups/backup-${DATE}.sql.gz"

              echo "Starting local backup to ${FILENAME}..."
              
              # Dump database and compress directly to the mounted volume
              PGPASSWORD="$POSTGRES_PASSWORD" pg_dump -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" | gzip > "$FILENAME"
              
              echo "Backup successfully saved locally to ${FILENAME}"
              ls -lh $FILENAME
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc