apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crypto-exchange.fullname" . }}
  labels:
    {{- include "crypto-exchange.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crypto-exchange.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crypto-exchange.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          command: ["gunicorn"]
          args:
            - "--bind"
            - "0.0.0.0:8000"
            - "CryptoCurrencyExchange.wsgi"
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "crypto-exchange.fullname" . }}-secrets
                  key: djangoSecretKey
            - name: DATABASE_URL
              value: "postgres://{{ .Values.database.user }}:$(DB_PASSWORD)@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "crypto-exchange.fullname" . }}-secrets
                  key: dbPassword
            - name: DJANGO_ALLOWED_HOSTS
              # Using a template function to ensure this line is parsed correctly
              value: {{ printf "%s,localhost,127.0.0.1" (first .Values.ingress.hosts).host }}