apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/sharare/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 06 Oct 2025 14:10:10 +0330
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:52999
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 06 Oct 2025 14:10:10 +0330
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /Users/sharare/.minikube/profiles/minikube/client.crt
    client-key: /Users/sharare/.minikube/profiles/minikube/client.key
